GET http://localhost:5167/api/errorhandling/error?numerator=10&denominator=2
###
GET http://localhost:5167/api/errorhandling/error?numerator=10&denominator=0
###
### Get all products
GET http://localhost:5167/api/products
Accept: application/json

###

### Get product by ID
GET http://localhost:5167/api/products/1
Accept: application/json

###

### Create new product
POST http://localhost:5167/api/products
Content-Type: application/json

{
  "name": "Laptop",
  "price": 999.99,
  "description": "A powerful laptop"
}

###

### Update existing product
PUT http://localhost:5167/api/products/1
Content-Type: application/json

{
  "name": "Gaming Laptop",
  "price": 1299.99,
  "description": "Upgraded with better GPU"
}

###

### Delete product by ID
DELETE http://localhost:5167/api/products/1



###
### serialization Test ####
GET http://localhost:5167/api/serialization/manual-json

###
### custom serializer ###
GET http://localhost:5167/api/serialization/custom-json

### json ###
GET http://localhost:5167/api/serialization/json

### auto ###
GET http://localhost:5167/api/serialization/auto


### Deserialization ###
POST http://localhost:5167/api/serialization/auto
Content-Type: application/json

{
  "UserName": "shivam",
  "Age": 26,
  "Gender": "male",
  "Email": "abc@gmail.com",
  "ExtraFeild":"extra value"
}

###

POST http://localhost:5167/api/serialization/json
Content-Type: application/json

{
  "UserName": "shivam",
  "Age": 26,
  "Gender": "male",
  "Email": "abcd@gmail.com",
  "ExtraFeild":"extra value"
}

###
POST http://localhost:5167/api/serialization/custom-json
Content-Type: application/json

{
  "UserName": "shivam",
  "Age": 26,
  "Gender": "male",
  "Email": "abcd@gmail.com",
  "ExtraFeild":"extra value"
}





